DELETE http://localhost:3000/api/scale/delete/5eb98a7a40045c310827471e

###

PUT  http://localhost:3000/api/scale/update
Content-Type: application/json

{
  "id": "5ebc23d53b8e895e507b1d23",
  "desc": "nowa tresc tej wiadomosci",
  "minFine": "190",
  "minPenaltyPoints": "2"
}

###

POST http://localhost:3000/api/scale/add
Content-Type: application/json

{
  "desc": "Opis nowego wykroczenia",
  "minPenaltyPoints": "0",
  "maxPenaltyPoints": "10",
  "minFine": "50",
  "maxFine": "200"
}

###

GET http://localhost:3000/api/scale/5ebc23d53b8e895e507b1d23

###

GET http://localhost:3000/api/scales